### ISSUE TITLE
Division by zero verifies as valid

### ISSUE THREAD

**Issue by dthaler** [vbpf/ebpf-verifier#133]
Source code of ebpf program:
```
int func()
{
   unsigned int zero = 0;
   return 100 / zero;
}
```

Invoking check using -v --no-simplify gives:
```
{r10 -> [512, +oo], off10 -> [512], t10 -> [-2], r1 -> [1, 2147418112], off1 -> [0], t1 -> [-3], packet_size -> [0, 65534], meta_offset -> [-4098, 0]
 }
Numbers -> {}
0:
  r1 = 0;
  goto 1;

{r10 -> [512, +oo], off10 -> [512], t10 -> [-2], r1 -> [0], t1 -> [-4], packet_size -> [0, 65534], meta_offset -> [-4098, 0]
 }
Numbers -> {}

{r10 -> [512, +oo], off10 -> [512], t10 -> [-2], r1 -> [0], t1 -> [-4], packet_size -> [0, 65534], meta_offset -> [-4098, 0]
 }
Numbers -> {}
1:
  assert valid_access(r10, -4:4);
  *(u32 *)(r10 - 4) = r1;
  goto 2;

{r10 -> [512, +oo], off10 -> [512], t10 -> [-2], r1 -> [0], S_t[-4...-1] -> [-4], t1 -> [-4], packet_size -> [0, 65534], meta_offset -> [-4098, 0]
 }
Numbers -> {[-4...-1]}

{r10 -> [512, +oo], off10 -> [512], t10 -> [-2], r1 -> [0], S_t[-4...-1] -> [-4], t1 -> [-4], packet_size -> [0, 65534], meta_offset -> [-4098, 0]
 }
Numbers -> {[-4...-1]}
2:
  assert valid_access(r10, -4:4);
  r1 = *(u32 *)(r10 - 4);
  goto 3;

{r10 -> [512, +oo], off10 -> [512], t10 -> [-2], S_t[-4...-1] -> [-4], t1 -> [-4], packet_size -> [0, 65534], meta_offset -> [-4098, 0]
 }
Numbers -> {[-4...-1]}

{r10 -> [512, +oo], off10 -> [512], t10 -> [-2], S_t[-4...-1] -> [-4], t1 -> [-4], packet_size -> [0, 65534], meta_offset -> [-4098, 0]
 }
Numbers -> {[-4...-1]}
3:
  r2 = 100;
  goto 4;

{r10 -> [512, +oo], off10 -> [512], t10 -> [-2], r2 -> [100], S_t[-4...-1] -> [-4], t1 -> [-4], packet_size -> [0, 65534], meta_offset -> [-4098, 0], t2 -> [-4]
 }
Numbers -> {[-4...-1]}

{r10 -> [512, +oo], off10 -> [512], t10 -> [-2], r2 -> [100], S_t[-4...-1] -> [-4], t1 -> [-4], packet_size -> [0, 65534], meta_offset -> [-4098, 0], t2 -> [-4]
 }
Numbers -> {[-4...-1]}
4:
  assert r2 : num;
  r2 /= r1;
  goto 5;

{r10 -> [512, +oo], off10 -> [512], t10 -> [-2], S_t[-4...-1] -> [-4], t1 -> [-4], packet_size -> [0, 65534], meta_offset -> [-4098, 0], t2 -> [-4]
 }
Numbers -> {[-4...-1]}

{r10 -> [512, +oo], off10 -> [512], t10 -> [-2], S_t[-4...-1] -> [-4], t1 -> [-4], packet_size -> [0, 65534], meta_offset -> [-4098, 0], t2 -> [-4]
 }
Numbers -> {[-4...-1]}
5:
  r0 = r2;
  goto 6;

{r10 -> [512, +oo], off10 -> [512], t10 -> [-2], S_t[-4...-1] -> [-4], t1 -> [-4], packet_size -> [0, 65534], meta_offset -> [-4098, 0], t2 -> [-4], t0 -> [-4]
 r2-r0<=0, r0-r2<=0, off2-off0<=0, off0-off2<=0}
Numbers -> {[-4...-1]}

{r10 -> [512, +oo], off10 -> [512], t10 -> [-2], S_t[-4...-1] -> [-4], t1 -> [-4], packet_size -> [0, 65534], meta_offset -> [-4098, 0], t2 -> [-4], t0 -> [-4]
 r2-r0<=0, r0-r2<=0, off2-off0<=0, off0-off2<=0}
Numbers -> {[-4...-1]}
6:
  assert r0 : num;
  exit;


{r10 -> [512, +oo], off10 -> [512], t10 -> [-2], S_t[-4...-1] -> [-4], t1 -> [-4], packet_size -> [0, 65534], meta_offset -> [-4098, 0], t2 -> [-4], t0 -> [-4]
 r2-r0<=0, r0-r2<=0, off2-off0<=0, off0-off2<=0}
Numbers -> {[-4...-1]}


0 warnings
1,0.006,4668
```

**Comment by dthaler** [comment]
Object file is at https://www.dropbox.com/s/wpobcbt3gh3ym6d/zero-var.o?dl=0

**Comment by elazarg** [comment]
This is intentional and is [documented in the code](https://github.com/vbpf/ebpf-verifier/blob/01c66cb4620522d7a319b554e5beea30e710e2c5/src/crab/ebpf_domain.hpp#L976). From the paper:
> Following the existing verifier, we treat division in a special way and check for division-by-zero errors at runtime.

See for example [this patch](https://patchwork.kernel.org/project/linux-arm-kernel/patch/1446620204-4228-1-git-send-email-zlim.lnx@gmail.com/):
```
In the case of division by zero in a BPF program:
	A = A / X;  (X == 0)
the expected behavior is to terminate with return value 0.

This is confirmed by the test case introduced in commit 86bf1721b226
("test_bpf: add tests checking that JIT/interpreter sets A and X to 0.").
```

Following discussions with Nadav Amit and others, I believe the main reasons for this decision are twofold:
- Division is rare and already expensive relatively to the simple runtime comparison to zero (practically no overhead, given OoOE in the CPU).
- The interval domain used by Linux cannot easily track "holes" in the range, so at least naively a check `r2 != 0` will give the Linux verifier nothing.

The latter point is true by definition for any convex domain, including Interval, Zone (which we use), Octagon and Polyhedra. These domain are more computationally tractable (well, in some sense) but fail to track "holes"; think about the constraints we have - `-5 <= y`, `y <= 5` - how do you encode also `y != 0`?

Crab does support some non-convex domains such as `boxes` and `dis_interval` (the former can verify our only "real" false positive in the benchmark), but they are usually significantly slower. I believe @caballa can give more information on those - and perhaps correct me if I'm wrong here. If you search for division by zero and program analysis you can find other interesting works on the subject, such as [donut domains](https://hal.archives-ouvertes.fr/hal-01660908/document).

We could in principle try to come up with some special domain for handling this particular case, and some others, but I don't think we should do that any time soon.

**Comment by caballa** [comment]
Yes, we can deal with division by zero without the need of expensive domains such as `boxes` or donut domains.
We could extend (via reduced product) zones with a simple domain such as `sign` or one that tracks only whether a variable can be zero or not.
I assume that the normal code will have the following pattern `if (x != 0) then ... /  x` so that should suffice. The domain `dis_interval` is cheap and it can be used for this but since efficiency is so important for us it's better something more specialized.

**Comment by elazarg** [comment]
In that case I stand corrected.

Nevertheless, adding this means we are rejecting val eBPF programs.

**Comment by dthaler** [comment]
Thanks for the explanation.  Verified the jitter handles it as Elazar explained.  Closing as by design.
