### ISSUE TITLE
ebpf_platform_t should also include a context which then should pe passed to the callback functions.

### ISSUE THREAD

**Issue by saxena-anurag** [vbpf/ebpf-verifier#224]
In order to support multiple calls to verifier in parallel, the callback functions provided in ebpf_platform_t should also be passed a context. ebpf_platform_t can include a new context structure which can then be passed to the callback functions.

**Comment by dthaler** [comment]
The verifier should already be threadsafe without passing any additional argument, because it's in a thread-local (for good or bad, that's what it is).

The information is in:
```
spec_type_descriptors.hpp:extern thread_local program_info global_program_info;
```

In the tests, test_verify.cpp tests multiple calls to the verifier in parallel, on different programs:
```
TEST_CASE("multithreading", "[verify][multithreading]")
```

I believe this issue can be closed as resolved, but feel free to reopen if you find any bugs/gaps.

**Comment by dthaler** [comment]
@elazarg recommend closing

**Comment by elazarg** [comment]
See #113
