### ISSUE TITLE
Regression in verifier output instruction count

### ISSUE THREAD

**Issue by shankarseal** [vbpf/ebpf-verifier#542]
[fbe8d16](https://github.com/vbpf/ebpf-verifier/commit/fbe8d16e7c00552212fbff5001c8b4c950b99d14) Bump external/ELFIO from 73a2410 to eb68829
[5924439](https://github.com/vbpf/ebpf-verifier/commit/59244394ae38e1b3241e945c28d0a122ec0714ef) Add support for signed division and modulo instructions
[ef234a6](https://github.com/vbpf/ebpf-verifier/commit/ef234a6f25b7ca2c551b5792cd0ec4039b9457a7) narrow to constant bounds once ([#479](https://redirect.github.com/vbpf/ebpf-verifier/issues/479))

One of the above commits seem to have regressed the verifier output.

```
Verification succeeded
  Program terminates within 0 instructions
```

Verification cannot possibly succeed with 0 instructions.

**Comment by dahavey** [comment]
@dv-msft will have a look at this issue.

**Comment by dthaler** [comment]
In PR #479, it appears from the following code:
```
bound_t ebpf_domain_t::get_instruction_count_upper_bound() {
    crab::bound_t ub{number_t{0}};
    for (variable_t counter : variable_t::get_instruction_counters())
        ub += std::max(ub, m_inv[counter].ub());
    return ub;
}
```
that the upper bound of the instruction count for a program execution is somehow the sum of instruction counters through the program.   However, this is not correct.  
Currently there's only a counter variable for the start of each loop, and no such counter for normal instructions.  As such, it currently returns a sum of loop iteration counts, not instruction counts.
So if you have a program that is like:

```
   do 20 instructions
   if (some condition) {
       ... do a loop with 10 iterations ...
   } else {
      ... do a different loop with 4 iterations ...
   }
```
it would return 10 + 4 = 14, which ignores the initial 20 instructions, and assumes that both the if and the else condition are executed, rather than only the max of them.
```
