### ISSUE TITLE
Cannot produce figures 9 and 10

### ISSUE THREAD

**Issue by oneturkmen** [vbpf/ebpf-verifier#97]
Hello,

Initially, I could not reproduce Figures 9/10 due to `scripts/makeplot.py` throwing a ValueError.

Here is an output:

```shell
Traceback (most recent call last):
  File "scripts/makeplot.py", line 13, in <module>
    data = np.genfromtxt(sys.argv[1], delimiter=',', names=True)
  File "/home/rahatly/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 2089, in genfromtxt
    raise ValueError(errmsg)
ValueError: Some errors were detected !
    Line #2 (got 26 columns instead of 45)
    Line #3 (got 26 columns instead of 45)
    Line #4 (got 26 columns instead of 45)
    Line #5 (got 26 columns instead of 45)
    ...
```

I removed last 19 columns which seemed to have empty rows. This fixed the problem.

Nevertheless, I still cannot reproduce figures 9 & 10. I attached the generated plots below. Would you suggest a fix or any other script I could take a look at?

Thanks!

![image](https://user-images.githubusercontent.com/17970732/69576079-d0b96000-0f88-11ea-984c-edd3c53b6bb1.png)

**Comment by oneturkmen** [comment]
cc @amirshukayev

**Comment by elazarg** [comment]
You can easily plot the data using excel or google sheets (just paste and "split data by columns", or load the `results.csv` file). IMO it's simpler and more easy to play with than the matplotlib version.

Note, however, that the current repository only has two domains: `zoneCrab` and `linux`. Also, zoneCrab got _much_ better since (particularly, it uses up to 100MB of ram instead of 1.3GB as in the paper); also the Linux verifier got much faster, and can unroll loops, so you will probably not get the same results on a new kernel.

If you want to reproduce the results from the paper as precisely as you can, and in particular if you want to compare the different numerical domains and implementations, then you should clone [the old version](https://github.com/vbpf/ebpf-verifier/tree/d29fd26345c3126bf166cf1c45233a9b2f9fb0a0) (there's also a link at the second line of the README file). Make sure to have a clean working directory and to clone the correct submodules recursively. If you already cloned the current version:
```bash
git checkout d29fd26345      # the paper's version
git submodule update         # cloning the Crab library: external/crab

make crab_install
make
scripts/runperf.sh ebpf-samples stats zoneCrab | tee results.csv
```

I could take a look at the `makeplot.py` script later, but you can just as well come up with your own - it was just something I used to play with. The charts in the paper were made using a LaTex plugin :)

Please let me know how it worked for you.

**Comment by oneturkmen** [comment]
@elazarg oh, yes. I missed that link on the README. Works now, thanks a lot! :)
